`define CONFIG_BIT CONFIG_Q_BIT+CONFIG_P_BIT+CONFIG_U_BIT+CONFIG_S_BIT+CONFIG_F_BIT+CONFIG_W_BIT
`define CONFIG_Q_START 0
`define CONFIG_P_START `CONFIG_Q_START + CONFIG_Q_BIT
`define CONFIG_U_START `CONFIG_P_START + CONFIG_P_BIT
`define CONFIG_S_START `CONFIG_U_START + CONFIG_U_BIT
`define CONFIG_F_START `CONFIG_S_START + CONFIG_S_BIT
`define CONFIG_W_START `CONFIG_F_START + CONFIG_F_BIT